// TODO: Refactor some of these into enums?
export const RESPONSE_CODE = {
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT_FOUND: 204,
  BAD_REQUEST: 400,
  FORBIDDEN: 403,
  REQUEST_TIMEOUT: 408,
  UNPROCESSABLE_ENTITY: 422,
};
export const RESPONSE_SUCCESS = true;
export const RESPONSE_FAILURE = false;

